apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-chatbot
  template:
    metadata:
      labels:
        app: pdf-chatbot
    spec:
      containers:
      - name: pdf-chatbot
        image: 985317222062.dkr.ecr.us-east-1.amazonaws.com/pdf-chatbot:latest
        ports:
        - containerPort: 8000
        env:
        - name: PINECONE_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: PINECONE_API_KEY
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OPENAI_API_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"